wikiminiatlas.js: Apply changes from the on-wiki version
https://meta.wikimedia.org/w/index.php?title=MediaWiki:Wikiminiatlas.js&diff=22661610&oldid=17619435

* maintenance: TypeError: e.data.split is not a function
* could be ?params= or &params=
* update translations
* add italian translations
* Add pashto translation by User:Af420
* using the WMCloud branding domain